// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/quangdung93/docs-hub-api/internal/module/user/domain"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/quangdung93/docs-hub-api/internal/common/pagination"

	usecase "github.com/quangdung93/docs-hub-api/internal/module/user/usecase"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockService) Create(ctx context.Context, in usecase.CreateInput) (*domain.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateInput) (*domain.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateInput) *domain.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.CreateInput
func (_e *MockService_Expecter) Create(ctx interface{}, in interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, in usecase.CreateInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *domain.User, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, usecase.CreateInput) (*domain.User, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id, version
func (_m *MockService) Delete(ctx context.Context, id uuid.UUID, version int) error {
	ret := _m.Called(ctx, id, version)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, id, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - version int
func (_e *MockService_Expecter) Delete(ctx interface{}, id interface{}, version interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, id, version)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, version int)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// EmailAvailable provides a mock function with given fields: ctx, email
func (_m *MockService) EmailAvailable(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for EmailAvailable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_EmailAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmailAvailable'
type MockService_EmailAvailable_Call struct {
	*mock.Call
}

// EmailAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockService_Expecter) EmailAvailable(ctx interface{}, email interface{}) *MockService_EmailAvailable_Call {
	return &MockService_EmailAvailable_Call{Call: _e.mock.On("EmailAvailable", ctx, email)}
}

func (_c *MockService_EmailAvailable_Call) Run(run func(ctx context.Context, email string)) *MockService_EmailAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_EmailAvailable_Call) Return(_a0 bool, _a1 error) *MockService_EmailAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_EmailAvailable_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockService_EmailAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockService) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockService_Expecter) GetByID(ctx interface{}, id interface{}) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(_a0 *domain.User, _a1 error) *MockService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.User, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, in
func (_m *MockService) List(ctx context.Context, in usecase.ListInput) ([]domain.User, pagination.Meta, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.User
	var r1 pagination.Meta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ListInput) ([]domain.User, pagination.Meta, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ListInput) []domain.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.ListInput) pagination.Meta); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Get(1).(pagination.Meta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, usecase.ListInput) error); ok {
		r2 = rf(ctx, in)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.ListInput
func (_e *MockService_Expecter) List(ctx interface{}, in interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, in)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, in usecase.ListInput)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.ListInput))
	})
	return _c
}

func (_c *MockService_List_Call) Return(_a0 []domain.User, _a1 pagination.Meta, _a2 error) *MockService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(context.Context, usecase.ListInput) ([]domain.User, pagination.Meta, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// SetStatus provides a mock function with given fields: ctx, in
func (_m *MockService) SetStatus(ctx context.Context, in usecase.SetStatusInput) (*domain.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for SetStatus")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SetStatusInput) (*domain.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.SetStatusInput) *domain.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.SetStatusInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_SetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatus'
type MockService_SetStatus_Call struct {
	*mock.Call
}

// SetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.SetStatusInput
func (_e *MockService_Expecter) SetStatus(ctx interface{}, in interface{}) *MockService_SetStatus_Call {
	return &MockService_SetStatus_Call{Call: _e.mock.On("SetStatus", ctx, in)}
}

func (_c *MockService_SetStatus_Call) Run(run func(ctx context.Context, in usecase.SetStatusInput)) *MockService_SetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.SetStatusInput))
	})
	return _c
}

func (_c *MockService_SetStatus_Call) Return(_a0 *domain.User, _a1 error) *MockService_SetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_SetStatus_Call) RunAndReturn(run func(context.Context, usecase.SetStatusInput) (*domain.User, error)) *MockService_SetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, in
func (_m *MockService) Update(ctx context.Context, in usecase.UpdateInput) (*domain.User, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateInput) (*domain.User, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateInput) *domain.User); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.UpdateInput
func (_e *MockService_Expecter) Update(ctx interface{}, in interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, in)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, in usecase.UpdateInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *domain.User, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, usecase.UpdateInput) (*domain.User, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
