// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/quangdung93/docs-hub-api/internal/module/project/domain"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/quangdung93/docs-hub-api/internal/common/pagination"

	usecase "github.com/quangdung93/docs-hub-api/internal/module/project/usecase"

	uuid "github.com/google/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// AcceptInvite provides a mock function with given fields: ctx, projectID, userID
func (_m *MockService) AcceptInvite(ctx context.Context, projectID uuid.UUID, userID uuid.UUID) (*domain.ProjectMember, error) {
	ret := _m.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AcceptInvite")
	}

	var r0 *domain.ProjectMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.ProjectMember, error)); ok {
		return rf(ctx, projectID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.ProjectMember); ok {
		r0 = rf(ctx, projectID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_AcceptInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcceptInvite'
type MockService_AcceptInvite_Call struct {
	*mock.Call
}

// AcceptInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) AcceptInvite(ctx interface{}, projectID interface{}, userID interface{}) *MockService_AcceptInvite_Call {
	return &MockService_AcceptInvite_Call{Call: _e.mock.On("AcceptInvite", ctx, projectID, userID)}
}

func (_c *MockService_AcceptInvite_Call) Run(run func(ctx context.Context, projectID uuid.UUID, userID uuid.UUID)) *MockService_AcceptInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_AcceptInvite_Call) Return(_a0 *domain.ProjectMember, _a1 error) *MockService_AcceptInvite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_AcceptInvite_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.ProjectMember, error)) *MockService_AcceptInvite_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeMemberRole provides a mock function with given fields: ctx, in
func (_m *MockService) ChangeMemberRole(ctx context.Context, in usecase.ChangeMemberRoleInput) (*domain.ProjectMember, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ChangeMemberRole")
	}

	var r0 *domain.ProjectMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ChangeMemberRoleInput) (*domain.ProjectMember, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.ChangeMemberRoleInput) *domain.ProjectMember); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.ChangeMemberRoleInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ChangeMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeMemberRole'
type MockService_ChangeMemberRole_Call struct {
	*mock.Call
}

// ChangeMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.ChangeMemberRoleInput
func (_e *MockService_Expecter) ChangeMemberRole(ctx interface{}, in interface{}) *MockService_ChangeMemberRole_Call {
	return &MockService_ChangeMemberRole_Call{Call: _e.mock.On("ChangeMemberRole", ctx, in)}
}

func (_c *MockService_ChangeMemberRole_Call) Run(run func(ctx context.Context, in usecase.ChangeMemberRoleInput)) *MockService_ChangeMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.ChangeMemberRoleInput))
	})
	return _c
}

func (_c *MockService_ChangeMemberRole_Call) Return(_a0 *domain.ProjectMember, _a1 error) *MockService_ChangeMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ChangeMemberRole_Call) RunAndReturn(run func(context.Context, usecase.ChangeMemberRoleInput) (*domain.ProjectMember, error)) *MockService_ChangeMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, in
func (_m *MockService) Create(ctx context.Context, in usecase.CreateProjectInput) (*domain.Project, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateProjectInput) (*domain.Project, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateProjectInput) *domain.Project); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateProjectInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.CreateProjectInput
func (_e *MockService_Expecter) Create(ctx interface{}, in interface{}) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", ctx, in)}
}

func (_c *MockService_Create_Call) Run(run func(ctx context.Context, in usecase.CreateProjectInput)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.CreateProjectInput))
	})
	return _c
}

func (_c *MockService_Create_Call) Return(_a0 *domain.Project, _a1 error) *MockService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(context.Context, usecase.CreateProjectInput) (*domain.Project, error)) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, in
func (_m *MockService) Delete(ctx context.Context, in usecase.DeleteProjectInput) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.DeleteProjectInput) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.DeleteProjectInput
func (_e *MockService_Expecter) Delete(ctx interface{}, in interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, in)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, in usecase.DeleteProjectInput)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.DeleteProjectInput))
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(_a0 error) *MockService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(context.Context, usecase.DeleteProjectInput) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// InviteMember provides a mock function with given fields: ctx, in
func (_m *MockService) InviteMember(ctx context.Context, in usecase.InviteMemberInput) (*domain.ProjectMember, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for InviteMember")
	}

	var r0 *domain.ProjectMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.InviteMemberInput) (*domain.ProjectMember, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.InviteMemberInput) *domain.ProjectMember); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.InviteMemberInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_InviteMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteMember'
type MockService_InviteMember_Call struct {
	*mock.Call
}

// InviteMember is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.InviteMemberInput
func (_e *MockService_Expecter) InviteMember(ctx interface{}, in interface{}) *MockService_InviteMember_Call {
	return &MockService_InviteMember_Call{Call: _e.mock.On("InviteMember", ctx, in)}
}

func (_c *MockService_InviteMember_Call) Run(run func(ctx context.Context, in usecase.InviteMemberInput)) *MockService_InviteMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.InviteMemberInput))
	})
	return _c
}

func (_c *MockService_InviteMember_Call) Return(_a0 *domain.ProjectMember, _a1 error) *MockService_InviteMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_InviteMember_Call) RunAndReturn(run func(context.Context, usecase.InviteMemberInput) (*domain.ProjectMember, error)) *MockService_InviteMember_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID, page
func (_m *MockService) List(ctx context.Context, userID uuid.UUID, page pagination.Query) ([]domain.Project, pagination.Meta, error) {
	ret := _m.Called(ctx, userID, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Project
	var r1 pagination.Meta
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Query) ([]domain.Project, pagination.Meta, error)); ok {
		return rf(ctx, userID, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Query) []domain.Project); ok {
		r0 = rf(ctx, userID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, pagination.Query) pagination.Meta); ok {
		r1 = rf(ctx, userID, page)
	} else {
		r1 = ret.Get(1).(pagination.Meta)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, pagination.Query) error); ok {
		r2 = rf(ctx, userID, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page pagination.Query
func (_e *MockService_Expecter) List(ctx interface{}, userID interface{}, page interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID, page)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID uuid.UUID, page pagination.Query)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(pagination.Query))
	})
	return _c
}

func (_c *MockService_List_Call) Return(_a0 []domain.Project, _a1 pagination.Meta, _a2 error) *MockService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, pagination.Query) ([]domain.Project, pagination.Meta, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, projectID
func (_m *MockService) ListMembers(ctx context.Context, projectID uuid.UUID) ([]domain.ProjectMember, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []domain.ProjectMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.ProjectMember, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.ProjectMember); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProjectMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockService_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockService_Expecter) ListMembers(ctx interface{}, projectID interface{}) *MockService_ListMembers_Call {
	return &MockService_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, projectID)}
}

func (_c *MockService_ListMembers_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockService_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_ListMembers_Call) Return(_a0 []domain.ProjectMember, _a1 error) *MockService_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.ProjectMember, error)) *MockService_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, projectID, userID
func (_m *MockService) RemoveMember(ctx context.Context, projectID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, projectID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockService_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) RemoveMember(ctx interface{}, projectID interface{}, userID interface{}) *MockService_RemoveMember_Call {
	return &MockService_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, projectID, userID)}
}

func (_c *MockService_RemoveMember_Call) Run(run func(ctx context.Context, projectID uuid.UUID, userID uuid.UUID)) *MockService_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockService_RemoveMember_Call) Return(_a0 error) *MockService_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockService_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, in
func (_m *MockService) Update(ctx context.Context, in usecase.UpdateProjectInput) (*domain.Project, error) {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateProjectInput) (*domain.Project, error)); ok {
		return rf(ctx, in)
	}
	if rf, ok := ret.Get(0).(func(context.Context, usecase.UpdateProjectInput) *domain.Project); ok {
		r0 = rf(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, usecase.UpdateProjectInput) error); ok {
		r1 = rf(ctx, in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.UpdateProjectInput
func (_e *MockService_Expecter) Update(ctx interface{}, in interface{}) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", ctx, in)}
}

func (_c *MockService_Update_Call) Run(run func(ctx context.Context, in usecase.UpdateProjectInput)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(usecase.UpdateProjectInput))
	})
	return _c
}

func (_c *MockService_Update_Call) Return(_a0 *domain.Project, _a1 error) *MockService_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(context.Context, usecase.UpdateProjectInput) (*domain.Project, error)) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
