// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	port "github.com/quangdung93/docs-hub-api/internal/common/port"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockObjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockObjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Delete(ctx interface{}, key interface{}) *MockObjectStore_Delete_Call {
	return &MockObjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockObjectStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Delete_Call) Return(_a0 error) *MockObjectStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockObjectStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockObjectStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Get(ctx context.Context, key string) ([]byte, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockObjectStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Get(ctx interface{}, key interface{}) *MockObjectStore_Get_Call {
	return &MockObjectStore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockObjectStore_Get_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Get_Call) Return(_a0 []byte, _a1 error) *MockObjectStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_Get_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockObjectStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedGetURL provides a mock function with given fields: ctx, key, ttl
func (_m *MockObjectStore) PresignedGetURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignedGetURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_PresignedGetURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedGetURL'
type MockObjectStore_PresignedGetURL_Call struct {
	*mock.Call
}

// PresignedGetURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockObjectStore_Expecter) PresignedGetURL(ctx interface{}, key interface{}, ttl interface{}) *MockObjectStore_PresignedGetURL_Call {
	return &MockObjectStore_PresignedGetURL_Call{Call: _e.mock.On("PresignedGetURL", ctx, key, ttl)}
}

func (_c *MockObjectStore_PresignedGetURL_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockObjectStore_PresignedGetURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockObjectStore_PresignedGetURL_Call) Return(_a0 string, _a1 error) *MockObjectStore_PresignedGetURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_PresignedGetURL_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockObjectStore_PresignedGetURL_Call {
	_c.Call.Return(run)
	return _c
}

// PresignedPutURL provides a mock function with given fields: ctx, key, ttl
func (_m *MockObjectStore) PresignedPutURL(ctx context.Context, key string, ttl time.Duration) (string, error) {
	ret := _m.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignedPutURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) (string, error)); ok {
		return rf(ctx, key, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) string); ok {
		r0 = rf(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = rf(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_PresignedPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignedPutURL'
type MockObjectStore_PresignedPutURL_Call struct {
	*mock.Call
}

// PresignedPutURL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockObjectStore_Expecter) PresignedPutURL(ctx interface{}, key interface{}, ttl interface{}) *MockObjectStore_PresignedPutURL_Call {
	return &MockObjectStore_PresignedPutURL_Call{Call: _e.mock.On("PresignedPutURL", ctx, key, ttl)}
}

func (_c *MockObjectStore_PresignedPutURL_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockObjectStore_PresignedPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockObjectStore_PresignedPutURL_Call) Return(_a0 string, _a1 error) *MockObjectStore_PresignedPutURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_PresignedPutURL_Call) RunAndReturn(run func(context.Context, string, time.Duration) (string, error)) *MockObjectStore_PresignedPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, key, data, contentType
func (_m *MockObjectStore) Put(ctx context.Context, key string, data []byte, contentType string) (port.StoredObject, error) {
	ret := _m.Called(ctx, key, data, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 port.StoredObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) (port.StoredObject, error)); ok {
		return rf(ctx, key, data, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, string) port.StoredObject); ok {
		r0 = rf(ctx, key, data, contentType)
	} else {
		r0 = ret.Get(0).(port.StoredObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, string) error); ok {
		r1 = rf(ctx, key, data, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockObjectStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - data []byte
//   - contentType string
func (_e *MockObjectStore_Expecter) Put(ctx interface{}, key interface{}, data interface{}, contentType interface{}) *MockObjectStore_Put_Call {
	return &MockObjectStore_Put_Call{Call: _e.mock.On("Put", ctx, key, data, contentType)}
}

func (_c *MockObjectStore_Put_Call) Run(run func(ctx context.Context, key string, data []byte, contentType string)) *MockObjectStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(string))
	})
	return _c
}

func (_c *MockObjectStore_Put_Call) Return(_a0 port.StoredObject, _a1 error) *MockObjectStore_Put_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_Put_Call) RunAndReturn(run func(context.Context, string, []byte, string) (port.StoredObject, error)) *MockObjectStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function with given fields: ctx, key
func (_m *MockObjectStore) Stat(ctx context.Context, key string) (port.StoredObject, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 port.StoredObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (port.StoredObject, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) port.StoredObject); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(port.StoredObject)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObjectStore_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockObjectStore_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockObjectStore_Expecter) Stat(ctx interface{}, key interface{}) *MockObjectStore_Stat_Call {
	return &MockObjectStore_Stat_Call{Call: _e.mock.On("Stat", ctx, key)}
}

func (_c *MockObjectStore_Stat_Call) Run(run func(ctx context.Context, key string)) *MockObjectStore_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockObjectStore_Stat_Call) Return(_a0 port.StoredObject, _a1 error) *MockObjectStore_Stat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObjectStore_Stat_Call) RunAndReturn(run func(context.Context, string) (port.StoredObject, error)) *MockObjectStore_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
