// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/quangdung93/docs-hub-api/internal/module/project/domain"
	mock "github.com/stretchr/testify/mock"

	pagination "github.com/quangdung93/docs-hub-api/internal/common/pagination"

	uuid "github.com/google/uuid"
)

// MockProjectRepository is an autogenerated mock type for the ProjectRepository type
type MockProjectRepository struct {
	mock.Mock
}

type MockProjectRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectRepository) EXPECT() *MockProjectRepository_Expecter {
	return &MockProjectRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockProjectRepository) Create(ctx context.Context, p *domain.Project) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Project
func (_e *MockProjectRepository_Expecter) Create(ctx interface{}, p interface{}) *MockProjectRepository_Create_Call {
	return &MockProjectRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockProjectRepository_Create_Call) Run(run func(ctx context.Context, p *domain.Project)) *MockProjectRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectRepository_Create_Call) Return(_a0 error) *MockProjectRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Project) error) *MockProjectRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProjectRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProjectRepository_Delete_Call {
	return &MockProjectRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProjectRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectRepository_Delete_Call) Return(_a0 error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockProjectRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockProjectRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Project, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Project, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Project); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockProjectRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProjectRepository_Expecter) FindByID(ctx interface{}, id interface{}) *MockProjectRepository_FindByID_Call {
	return &MockProjectRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockProjectRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProjectRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectRepository_FindByID_Call) Return(_a0 *domain.Project, _a1 error) *MockProjectRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Project, error)) *MockProjectRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListForUser provides a mock function with given fields: ctx, userID, page
func (_m *MockProjectRepository) ListForUser(ctx context.Context, userID uuid.UUID, page pagination.Query) ([]domain.Project, int64, error) {
	ret := _m.Called(ctx, userID, page)

	if len(ret) == 0 {
		panic("no return value specified for ListForUser")
	}

	var r0 []domain.Project
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Query) ([]domain.Project, int64, error)); ok {
		return rf(ctx, userID, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, pagination.Query) []domain.Project); ok {
		r0 = rf(ctx, userID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, pagination.Query) int64); ok {
		r1 = rf(ctx, userID, page)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, pagination.Query) error); ok {
		r2 = rf(ctx, userID, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockProjectRepository_ListForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListForUser'
type MockProjectRepository_ListForUser_Call struct {
	*mock.Call
}

// ListForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - page pagination.Query
func (_e *MockProjectRepository_Expecter) ListForUser(ctx interface{}, userID interface{}, page interface{}) *MockProjectRepository_ListForUser_Call {
	return &MockProjectRepository_ListForUser_Call{Call: _e.mock.On("ListForUser", ctx, userID, page)}
}

func (_c *MockProjectRepository_ListForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, page pagination.Query)) *MockProjectRepository_ListForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(pagination.Query))
	})
	return _c
}

func (_c *MockProjectRepository_ListForUser_Call) Return(_a0 []domain.Project, _a1 int64, _a2 error) *MockProjectRepository_ListForUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockProjectRepository_ListForUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, pagination.Query) ([]domain.Project, int64, error)) *MockProjectRepository_ListForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockProjectRepository) Update(ctx context.Context, p *domain.Project) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Project) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Project
func (_e *MockProjectRepository_Expecter) Update(ctx interface{}, p interface{}) *MockProjectRepository_Update_Call {
	return &MockProjectRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockProjectRepository_Update_Call) Run(run func(ctx context.Context, p *domain.Project)) *MockProjectRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Project))
	})
	return _c
}

func (_c *MockProjectRepository_Update_Call) Return(_a0 error) *MockProjectRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Project) error) *MockProjectRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectRepository creates a new instance of MockProjectRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectRepository {
	mock := &MockProjectRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
