// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/quangdung93/docs-hub-api/internal/module/project/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockProjectMemberRepository is an autogenerated mock type for the ProjectMemberRepository type
type MockProjectMemberRepository struct {
	mock.Mock
}

type MockProjectMemberRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectMemberRepository) EXPECT() *MockProjectMemberRepository_Expecter {
	return &MockProjectMemberRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, m
func (_m *MockProjectMemberRepository) Create(ctx context.Context, m *domain.ProjectMember) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProjectMember) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectMemberRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectMemberRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - m *domain.ProjectMember
func (_e *MockProjectMemberRepository_Expecter) Create(ctx interface{}, m interface{}) *MockProjectMemberRepository_Create_Call {
	return &MockProjectMemberRepository_Create_Call{Call: _e.mock.On("Create", ctx, m)}
}

func (_c *MockProjectMemberRepository_Create_Call) Run(run func(ctx context.Context, m *domain.ProjectMember)) *MockProjectMemberRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ProjectMember))
	})
	return _c
}

func (_c *MockProjectMemberRepository_Create_Call) Return(_a0 error) *MockProjectMemberRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectMemberRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.ProjectMember) error) *MockProjectMemberRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, projectID, userID
func (_m *MockProjectMemberRepository) Delete(ctx context.Context, projectID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, projectID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectMemberRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectMemberRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - userID uuid.UUID
func (_e *MockProjectMemberRepository_Expecter) Delete(ctx interface{}, projectID interface{}, userID interface{}) *MockProjectMemberRepository_Delete_Call {
	return &MockProjectMemberRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, projectID, userID)}
}

func (_c *MockProjectMemberRepository_Delete_Call) Run(run func(ctx context.Context, projectID uuid.UUID, userID uuid.UUID)) *MockProjectMemberRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectMemberRepository_Delete_Call) Return(_a0 error) *MockProjectMemberRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectMemberRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockProjectMemberRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByProjectAndUser provides a mock function with given fields: ctx, projectID, userID
func (_m *MockProjectMemberRepository) FindByProjectAndUser(ctx context.Context, projectID uuid.UUID, userID uuid.UUID) (*domain.ProjectMember, error) {
	ret := _m.Called(ctx, projectID, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProjectAndUser")
	}

	var r0 *domain.ProjectMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*domain.ProjectMember, error)); ok {
		return rf(ctx, projectID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *domain.ProjectMember); ok {
		r0 = rf(ctx, projectID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProjectMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectMemberRepository_FindByProjectAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByProjectAndUser'
type MockProjectMemberRepository_FindByProjectAndUser_Call struct {
	*mock.Call
}

// FindByProjectAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - userID uuid.UUID
func (_e *MockProjectMemberRepository_Expecter) FindByProjectAndUser(ctx interface{}, projectID interface{}, userID interface{}) *MockProjectMemberRepository_FindByProjectAndUser_Call {
	return &MockProjectMemberRepository_FindByProjectAndUser_Call{Call: _e.mock.On("FindByProjectAndUser", ctx, projectID, userID)}
}

func (_c *MockProjectMemberRepository_FindByProjectAndUser_Call) Run(run func(ctx context.Context, projectID uuid.UUID, userID uuid.UUID)) *MockProjectMemberRepository_FindByProjectAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectMemberRepository_FindByProjectAndUser_Call) Return(_a0 *domain.ProjectMember, _a1 error) *MockProjectMemberRepository_FindByProjectAndUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectMemberRepository_FindByProjectAndUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*domain.ProjectMember, error)) *MockProjectMemberRepository_FindByProjectAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListByProject provides a mock function with given fields: ctx, projectID
func (_m *MockProjectMemberRepository) ListByProject(ctx context.Context, projectID uuid.UUID) ([]domain.MemberWithUser, error) {
	ret := _m.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ListByProject")
	}

	var r0 []domain.MemberWithUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.MemberWithUser, error)); ok {
		return rf(ctx, projectID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.MemberWithUser); ok {
		r0 = rf(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MemberWithUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProjectMemberRepository_ListByProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByProject'
type MockProjectMemberRepository_ListByProject_Call struct {
	*mock.Call
}

// ListByProject is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
func (_e *MockProjectMemberRepository_Expecter) ListByProject(ctx interface{}, projectID interface{}) *MockProjectMemberRepository_ListByProject_Call {
	return &MockProjectMemberRepository_ListByProject_Call{Call: _e.mock.On("ListByProject", ctx, projectID)}
}

func (_c *MockProjectMemberRepository_ListByProject_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockProjectMemberRepository_ListByProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockProjectMemberRepository_ListByProject_Call) Return(_a0 []domain.MemberWithUser, _a1 error) *MockProjectMemberRepository_ListByProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProjectMemberRepository_ListByProject_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]domain.MemberWithUser, error)) *MockProjectMemberRepository_ListByProject_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, projectID, userID, role
func (_m *MockProjectMemberRepository) UpdateRole(ctx context.Context, projectID uuid.UUID, userID uuid.UUID, role domain.Role) error {
	ret := _m.Called(ctx, projectID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, domain.Role) error); ok {
		r0 = rf(ctx, projectID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectMemberRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockProjectMemberRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID uuid.UUID
//   - userID uuid.UUID
//   - role domain.Role
func (_e *MockProjectMemberRepository_Expecter) UpdateRole(ctx interface{}, projectID interface{}, userID interface{}, role interface{}) *MockProjectMemberRepository_UpdateRole_Call {
	return &MockProjectMemberRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, projectID, userID, role)}
}

func (_c *MockProjectMemberRepository_UpdateRole_Call) Run(run func(ctx context.Context, projectID uuid.UUID, userID uuid.UUID, role domain.Role)) *MockProjectMemberRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(domain.Role))
	})
	return _c
}

func (_c *MockProjectMemberRepository_UpdateRole_Call) Return(_a0 error) *MockProjectMemberRepository_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectMemberRepository_UpdateRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, domain.Role) error) *MockProjectMemberRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, m
func (_m *MockProjectMemberRepository) UpdateStatus(ctx context.Context, m *domain.ProjectMember) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProjectMember) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProjectMemberRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockProjectMemberRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - m *domain.ProjectMember
func (_e *MockProjectMemberRepository_Expecter) UpdateStatus(ctx interface{}, m interface{}) *MockProjectMemberRepository_UpdateStatus_Call {
	return &MockProjectMemberRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, m)}
}

func (_c *MockProjectMemberRepository_UpdateStatus_Call) Run(run func(ctx context.Context, m *domain.ProjectMember)) *MockProjectMemberRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ProjectMember))
	})
	return _c
}

func (_c *MockProjectMemberRepository_UpdateStatus_Call) Return(_a0 error) *MockProjectMemberRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProjectMemberRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, *domain.ProjectMember) error) *MockProjectMemberRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProjectMemberRepository creates a new instance of MockProjectMemberRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectMemberRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectMemberRepository {
	mock := &MockProjectMemberRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
