// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/quangdung93/docs-hub-api/internal/module/auth/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/quangdung93/docs-hub-api/internal/module/auth/usecase"

	uuid "github.com/google/uuid"
)

// MockAuthUseCase is an autogenerated mock type for the AuthUseCase type
type MockAuthUseCase struct {
	mock.Mock
}

type MockAuthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthUseCase) EXPECT() *MockAuthUseCase_Expecter {
	return &MockAuthUseCase_Expecter{mock: &_m.Mock}
}

// GetMe provides a mock function with given fields: ctx, userID
func (_m *MockAuthUseCase) GetMe(ctx context.Context, userID string) (*domain.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthUseCase_GetMe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMe'
type MockAuthUseCase_GetMe_Call struct {
	*mock.Call
}

// GetMe is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAuthUseCase_Expecter) GetMe(ctx interface{}, userID interface{}) *MockAuthUseCase_GetMe_Call {
	return &MockAuthUseCase_GetMe_Call{Call: _e.mock.On("GetMe", ctx, userID)}
}

func (_c *MockAuthUseCase_GetMe_Call) Run(run func(ctx context.Context, userID string)) *MockAuthUseCase_GetMe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_GetMe_Call) Return(_a0 *domain.User, _a1 error) *MockAuthUseCase_GetMe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthUseCase_GetMe_Call) RunAndReturn(run func(context.Context, string) (*domain.User, error)) *MockAuthUseCase_GetMe_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *MockAuthUseCase) Login(ctx context.Context, username string, password string) (*domain.User, usecase.TokenPair, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.User
	var r1 usecase.TokenPair
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, usecase.TokenPair, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) usecase.TokenPair); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Get(1).(usecase.TokenPair)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, username, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthUseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthUseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthUseCase_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockAuthUseCase_Login_Call {
	return &MockAuthUseCase_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAuthUseCase_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthUseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_Login_Call) Return(_a0 *domain.User, _a1 usecase.TokenPair, _a2 error) *MockAuthUseCase_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthUseCase_Login_Call) RunAndReturn(run func(context.Context, string, string) (*domain.User, usecase.TokenPair, error)) *MockAuthUseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, userID, refreshToken, accessToken
func (_m *MockAuthUseCase) Logout(ctx context.Context, userID uuid.UUID, refreshToken string, accessToken string) error {
	ret := _m.Called(ctx, userID, refreshToken, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) error); ok {
		r0 = rf(ctx, userID, refreshToken, accessToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthUseCase_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthUseCase_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - refreshToken string
//   - accessToken string
func (_e *MockAuthUseCase_Expecter) Logout(ctx interface{}, userID interface{}, refreshToken interface{}, accessToken interface{}) *MockAuthUseCase_Logout_Call {
	return &MockAuthUseCase_Logout_Call{Call: _e.mock.On("Logout", ctx, userID, refreshToken, accessToken)}
}

func (_c *MockAuthUseCase_Logout_Call) Run(run func(ctx context.Context, userID uuid.UUID, refreshToken string, accessToken string)) *MockAuthUseCase_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_Logout_Call) Return(_a0 error) *MockAuthUseCase_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthUseCase_Logout_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string) error) *MockAuthUseCase_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthUseCase) Refresh(ctx context.Context, refreshToken string) (*domain.User, usecase.TokenPair, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *domain.User
	var r1 usecase.TokenPair
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, usecase.TokenPair, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) usecase.TokenPair); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Get(1).(usecase.TokenPair)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, refreshToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthUseCase_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthUseCase_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthUseCase_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *MockAuthUseCase_Refresh_Call {
	return &MockAuthUseCase_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockAuthUseCase_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthUseCase_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthUseCase_Refresh_Call) Return(_a0 *domain.User, _a1 usecase.TokenPair, _a2 error) *MockAuthUseCase_Refresh_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthUseCase_Refresh_Call) RunAndReturn(run func(context.Context, string) (*domain.User, usecase.TokenPair, error)) *MockAuthUseCase_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthUseCase creates a new instance of MockAuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthUseCase {
	mock := &MockAuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
